blank_issues_enabled: true
contact_links:
  - name: TON Metaspace Support
    url: https://github.com/orgs/tonmetaspace/discussions
    about: Please ask and answer questions here.
  - name: TON Metaspace Security Bug Bounty
    url: https://github.com/tonmetaspace
    about: Please report security vulnerabilities here.
